name: Linter

on:
  - push
  - pull_request

jobs:
  eslint:
    name: Linter
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run:
            npm install eslint
            npm install eslint-config-airbnb-base
            npm install eslint-plugin-import

      - name: Run linter
        run: make lint
